name = "wfsl-licence-authority"
main = "cloudflare/licence-api.ts"
compatibility_date = "2024-11-01"
workers_dev = true

account_id = "35fc8a6f1d27ca35d930549ee5e26e1d"

[[kv_namespaces]]
binding = "LICENCE_REG"
id = "a9eb3cf517894639aac19cb48629ca70"

[[kv_namespaces]]
binding = "WFSL_REVOKED"
id = "338d12efa4944eb8976082ad37605a0b"

[[kv_namespaces]]
binding = "WFSL_LOGS"
id = "26cdda4781c041e7ab0e957819e9d46f"
